name: maykay
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.7+15

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.2
  path_provider: ^2.1.4
  url_launcher: ^6.3.0
  photo_view: ^0.15.0
  logger: ^2.5.0
  easy_localization: ^3.0.3

  # 🔥 Firebase – najnowsze stabilne
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  firebase_messaging: ^16.0.2
  firebase_analytics: ^12.0.2

  mobile_scanner: ^7.0.2
  permission_handler: ^12.0.0
  http: ^1.3.0
  webview_flutter: ^4.13.0
  flutter_dotenv: ^6.0.0
  video_player: ^2.9.1
  cupertino_icons: ^1.0.8
  flutter_phoenix: ^1.1.1
  flutter_local_notifications: ^19.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/translations/
    - assets/maykay.env

# Launcher icons – zostają jak były
flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: "assets/Logo2.png"
  image_path_ios: "assets/Ikon.png"

# Splash z białym tłem
flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#FFFFFF"
  image: assets/images/bg_logo.png
  image_dark: assets/images/bg_logo.png

  android_12:
    image: assets/images/bg_logo.png
    image_dark: assets/images/bg_logo.png
    icon_background_color: "#FFFFFF"
    icon_background_color_dark: "#FFFFFF"

  android_gravity: center
  fullscreen: false
